package net.dsh.createmite.kinetics.client;

/** Brass encased models (generated by tools.ModelGen from the original create jar). */
public final class CreateModelsBrass {
    private CreateModelsBrass() {}

// ===== BRASS_ENCASED_COGWHEEL ��ͼ�� =====
//   0 -> minecraft:block/stripped_dark_oak_log_top
//   1 -> create:block/brass_gearbox
//   2 -> create:block/brass_casing
//   3 -> create:block/brass_encased_cogwheel_side

// ===== BRASS_ENCASED_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side

// ===== BRASS_ENCASED_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side

// ===== BRASS_ENCASED_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side

// ===== BRASS_ENCASED_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side

    public static final CreateModels.El[] BRASS_ENCASED_COGWHEEL = {

        new CreateModels.El(0F, 1F, 0F, 16F, 6F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{23, 30, 27, 27, 27, 27},

              new float[][]{{0F,0F,16F,16F}, {0F,0F,16F,16F}, {0F,10F,16F,15F}, {0F,10F,16F,15F}, {0F,10F,16F,15F}, {0F,10F,16F,15F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 6F, 0F, 16F, 10F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 4, 27, 27, 27, 27},

              new float[][]{null, null, {0F,6F,16F,10F}, {0F,6F,16F,10F}, {0F,6F,16F,10F}, {0F,6F,16F,10F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(15.95F, 6F, 0.05F, 0.05F, 10F, 15.95F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 4, 27, 27, 27, 27},

              new float[][]{null, null, {0F,6F,16F,10F}, {0F,6F,16F,10F}, {0F,6F,16F,10F}, {0F,6F,16F,10F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 10F, 0F, 16F, 15F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{30, 23, 27, 27, 27, 27},

              new float[][]{{0F,0F,16F,16F}, {0F,0F,16F,16F}, {0F,1F,16F,6F}, {0F,1F,16F,6F}, {0F,1F,16F,6F}, {0F,1F,16F,6F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 0F, 16F, 16F, 2F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 4, 27, 25, 27, 27},

              new float[][]{{0F,0F,16F,2F}, null, {0F,0F,16F,1F}, {0F,0F,16F,1F}, {0F,0F,2F,1F}, {14F,0F,16F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 14F, 16F, 16F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 4, 25, 27, 27, 27},

              new float[][]{{0F,14F,16F,16F}, null, {0F,0F,16F,1F}, {0F,0F,16F,1F}, {14F,0F,16F,1F}, {0F,0F,2F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 2F, 2F, 16F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 4, 4, 4, 27, 25},

              new float[][]{{0F,2F,2F,14F}, null, null, null, {2F,0F,14F,1F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(14F, 15F, 2F, 16F, 16F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 4, 4, 4, 25, 27},

              new float[][]{{14F,2F,16F,14F}, null, null, null, {2F,0F,14F,1F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 0F, 16F, 1F, 2F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 27, 25, 27, 27},

              new float[][]{null, {0F,14F,16F,16F}, {0F,15F,16F,16F}, {0F,0F,16F,1F}, {0F,15F,2F,16F}, {14F,15F,16F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(14F, 0F, 2F, 16F, 1F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 4, 4, 25, 27},

              new float[][]{null, {14F,2F,16F,14F}, null, null, {2F,0F,14F,1F}, {2F,15F,14F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 14F, 16F, 1F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 25, 27, 27, 27},

              new float[][]{null, {0F,0F,16F,2F}, {0F,0F,16F,1F}, {0F,15F,16F,16F}, {14F,15F,16F,16F}, {0F,15F,2F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 2F, 2F, 1F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 4, 4, 27, 25},

              new float[][]{null, {0F,2F,2F,14F}, null, null, {2F,15F,14F,16F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

    };






// ===== BRASS_ENCASED_LARGE_COGWHEEL ��ͼ�� =====
//   0 -> minecraft:block/stripped_dark_oak_log_top
//   1 -> create:block/brass_gearbox
//   2 -> create:block/brass_casing
//   3 -> create:block/brass_encased_cogwheel_side_connected

// ===== BRASS_ENCASED_LARGE_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side_connected

// ===== BRASS_ENCASED_LARGE_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side_connected

// ===== BRASS_ENCASED_LARGE_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side_connected

// ===== BRASS_ENCASED_LARGE_COGWHEEL ��ͼ�� =====

//   0 -> minecraft:block/stripped_dark_oak_log_top

//   1 -> create:block/brass_gearbox

//   2 -> create:block/brass_casing

//   3 -> create:block/brass_encased_cogwheel_side_connected

    public static final CreateModels.El[] BRASS_ENCASED_LARGE_COGWHEEL = {

        new CreateModels.El(0F, 1F, 0F, 16F, 6F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{23, 30, 29, 29, 29, 29},

              new float[][]{{0F,0F,16F,16F}, {0F,0F,16F,16F}, {8F,13F,16F,15.5F}, {8F,13F,16F,15.5F}, {8F,13F,16F,15.5F}, {8F,13F,16F,15.5F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        // 同安山版：原版中带 4px 是开口，这里补一圈中带，免得看穿方块
        new CreateModels.El(0F, 6F, 0F, 16F, 10F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{30, 30, 29, 29, 29, 29},

              new float[][]{null, null, {8F,11F,16F,13F}, {8F,11F,16F,13F}, {8F,11F,16F,13F}, {8F,11F,16F,13F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 10F, 0F, 16F, 15F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{30, 23, 29, 29, 29, 29},

              new float[][]{{0F,0F,16F,16F}, {0F,0F,16F,16F}, {8F,8.5F,16F,11F}, {8F,8.5F,16F,11F}, {8F,8.5F,16F,11F}, {8F,8.5F,16F,11F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(14F, 15F, 2F, 16F, 16F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 25, 25, 25, 25, 25},

              new float[][]{{14F,2F,16F,14F}, {0F,0F,0F,0F}, {0F,0F,0F,0F}, {0F,0F,0F,0F}, {2F,0F,14F,1F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 0F, 16F, 16F, 2F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 25, 25, 25, 25, 25},

              new float[][]{{0F,0F,16F,2F}, {0F,0F,0F,0F}, {0F,0F,16F,1F}, {0F,0F,16F,1F}, {0F,0F,2F,1F}, {14F,0F,16F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 2F, 2F, 16F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 25, 25, 25, 25, 25},

              new float[][]{{0F,2F,2F,14F}, {0F,0F,0F,0F}, {0F,0F,0F,0F}, {0F,0F,0F,0F}, {2F,0F,14F,1F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 15F, 14F, 16F, 16F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{25, 25, 25, 25, 25, 25},

              new float[][]{{0F,14F,16F,16F}, {0F,0F,0F,0F}, {0F,0F,16F,1F}, {0F,0F,16F,1F}, {14F,0F,16F,1F}, {0F,0F,2F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 0F, 16F, 1F, 2F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 25, 25, 25, 25},

              new float[][]{null, {0F,14F,16F,16F}, {0F,15F,16F,16F}, {0F,0F,16F,1F}, {0F,15F,2F,16F}, {14F,15F,16F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(14F, 0F, 2F, 16F, 1F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 4, 4, 25, 25},

              new float[][]{null, {14F,2F,16F,14F}, null, null, {2F,0F,14F,1F}, {2F,15F,14F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 2F, 2F, 1F, 14F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 4, 4, 25, 25},

              new float[][]{null, {0F,2F,2F,14F}, null, null, {2F,15F,14F,16F}, {2F,0F,14F,1F}},

              new int[]{0, 0, 0, 0, 0, 0}),

        new CreateModels.El(0F, 0F, 14F, 16F, 1F, 16F, 0F, 1, 8F, 8F, 8F,

              new int[]{4, 25, 25, 25, 25, 25},

              new float[][]{null, {0F,0F,16F,2F}, {0F,0F,16F,1F}, {0F,15F,16F,16F}, {14F,15F,16F,16F}, {0F,15F,2F,16F}},

              new int[]{0, 0, 0, 0, 0, 0}),

    };





//   0 -> create:block/brass_casing
//   1 -> create:block/brass_gearbox

// ===== BRASS_ENCASED_SHAFT ��ͼ�� =====

//   0 -> create:block/brass_casing

//   1 -> create:block/brass_gearbox

// ===== BRASS_ENCASED_SHAFT ��ͼ�� =====

//   0 -> create:block/brass_casing

//   1 -> create:block/brass_gearbox

// ===== BRASS_ENCASED_SHAFT ��ͼ�� =====

//   0 -> create:block/brass_casing

//   1 -> create:block/brass_gearbox

// ===== BRASS_ENCASED_SHAFT ��ͼ�� =====
//   0 -> create:block/brass_casing
//   1 -> create:block/brass_gearbox
    public static final CreateModels.El[] BRASS_ENCASED_SHAFT = {
        new CreateModels.El(0F, 0F, 0F, 16F, 16F, 2F, 0F, 1, 8F, 8F, 8F,
              new int[]{25, 25, 25, 25, 25, 25},
              new float[][]{{0F,14F,16F,16F}, {0F,14F,16F,16F}, {0F,0F,16F,16F}, {0F,0F,16F,16F}, {0F,0F,2F,16F}, {14F,0F,16F,16F}},
              new int[]{180, 0, 0, 0, 0, 0}),
        new CreateModels.El(1F, 0.95F, 2F, 15F, 15.05F, 14F, 0F, 1, 8F, 8F, 8F,
              new int[]{4, 4, 4, 4, 4, 4},
              new float[][]{{1F,2F,15F,14F}, {1F,2F,15F,14F}, null, null, null, null},
              new int[]{180, 0, 0, 0, 0, 0}),
        new CreateModels.El(0F, 0F, 14F, 16F, 16F, 16F, 0F, 1, 8F, 8F, 8F,
              new int[]{25, 25, 25, 25, 25, 25},
              new float[][]{{0F,0F,16F,2F}, {0F,0F,16F,2F}, {0F,0F,16F,16F}, {0F,0F,16F,16F}, {14F,0F,16F,16F}, {0F,0F,2F,16F}},
              new int[]{180, 0, 0, 0, 0, 0}),
        new CreateModels.El(0F, 0F, 2F, 2F, 16F, 14F, 0F, 1, 8F, 8F, 8F,
              new int[]{25, 25, 4, 4, 25, 25},
              new float[][]{{14F,2F,16F,14F}, {0F,2F,2F,14F}, null, null, {2F,0F,14F,16F}, {2F,0F,14F,16F}},
              new int[]{180, 0, 0, 0, 0, 0}),
        new CreateModels.El(14F, 0F, 2F, 16F, 16F, 14F, 0F, 1, 8F, 8F, 8F,
              new int[]{25, 25, 4, 4, 25, 25},
              new float[][]{{0F,2F,2F,14F}, {14F,2F,16F,14F}, null, null, {2F,0F,14F,16F}, {2F,0F,14F,16F}},
              new int[]{180, 0, 0, 0, 0, 0}),
    };





}